### ISSUE TITLE
Javascript is not generated correctly when using custom form prefixes

### ISSUE THREAD

**Issue by corsairmoran** [digi604/django-smart-selects#1]
When a Django model has a ChainedForeignKey, and the Django form used for displaying a uses a custom prefix via a prefix keyword argument, the javascript output for the form's ChainedModelChoiceField does not take this prefix into account. Thus the generated javascript fails as the id of the "chained_field" does not match with the id used in the javascript.

**Comment by blag** [comment]
Should be fixed in #148. Closing. Feel free to reopen if it's not fixed.
