### ISSUE TITLE
Chained selection not working in admin

### ISSUE THREAD

**Issue by zhou0031** [digi604/django-smart-selects#10]
```python
class Continent(models.Model):
	continent=models.CharField(max_length=20)

class Country(models.Model):
	country= models.CharField(max_length=20)
	continent=ChainedForeignKey(Continent,chained_field="continent", chained_model_field="continent")

class State(models.Model):
	state=models.CharField(max_length=20)
        country = ChainedForeignKey(Country,chained_field="country", chained_model_field="country")

class City(models.Model):
	city=models.CharField(max_length=20)
        state=ChainedForeignKey(State,chained_field="state", chained_model_field="state")

class District(models.Model):
	district = models.CharField(max_length=20)
        city=ChainedForeignKey(City,chained_field="city", chained_model_field="city")
```

--------------------------------------------------------------------------------------------------------------------------------------
Hello.
Above is my code using your app. I now have 2 issues

1. When I add country in admin. I can't assign  the continent to each country because the continent is not in the list 
2. If I select United States, all states don't show in the dropdown list. Can you take a look?

THanks from Canada

Edit (by blag): Formatted with GFM.

**Comment by SalahAdDin** [comment]
Don't works yet, could you solve this issue?

**Comment by blag** [comment]
Closing since it's been 6 years. Reopen if you are still having issues.
