### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jpfabris** [digi604/django-smart-selects#102]
I need some information about the ChainedModelChoiceField from form_fields module. How can I use in forms.py? I want to extend it and I can't even make it work. Please expand documentation to forms.py.

**Comment by arkadyzalko** [comment]
That'd be great! ChainedModelChoiceField from forms has many possibilities of usage in Django projects. This is a great library to focus documentation just in the model scope. :thumbsup:

**Comment by SalahAdDin** [comment]
:+1:

**Comment by blag** [comment]
Is there a specific question you have about how to use the form fields without using the database fields? The intent of this package is that you specify `Chained*` relations in your `models.py` and  your forms Just Work <sup>TM</sup>, and you haven't specified how exactly you're trying to use this without your `models.py` or asked a specific question so I can't really figure out what information would help you.

Closing, but feel free to ask a more specific question and reopen.
