### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by PetrDlouhy** [digi604/django-smart-selects#104]
There is possible future problem with Django 1.10 warning
```
/home/petr/soubory/programovani/Auto-mat/DPNK/dpnk/env/src/django-smart-selects/smart_selects/urls.py:9: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got filterchain_all). Pass the callable instead.
```

**Comment by aroraumang** [comment]
Hi. I've sent a pull request to fix this issue. Can someone please review and merge? Thanks :)
https://github.com/digi604/django-smart-selects/pull/105

**Comment by aroraumang** [comment]
@jimmykobe1171 Can you please check the PR I've sent to fix this issue and make a release with it? Thanks :)
https://github.com/digi604/django-smart-selects/pull/105

**Comment by PetrDlouhy** [comment]
I have tested this, and it works fine.

**Comment by jimmykobe1171** [comment]
ok, I will merge this in a few days.

**Comment by aroraumang** [comment]
Thanks

**Comment by PetrDlouhy** [comment]
@aroraumang BTW. This project doesn't have any tests. I think, that adding few tests would help this project a lot.

**Comment by aroraumang** [comment]
Great :D
I'll take a look in my free time and write more tests if required :+1:

**Comment by jimmykobe1171** [comment]
Yes, I also want to write tests. But I am busy this month. Tell me if you have written.

**Comment by aroraumang** [comment]
Sure :+1:

**Comment by PetrDlouhy** [comment]
Hi, I have quickly added at least the Travis and Coveralls configuration in PR #108. It doesn't test much, but better than nothing.

**Comment by jimmykobe1171** [comment]
That's great! Thank u so much：)

**Comment by PetrDlouhy** [comment]
I am closing this PR, because the PR #108 overcome this one.
