### ISSUE TITLE
No selectable items in required fields

### ISSUE THREAD

**Issue by artamoshin** [digi604/django-smart-selects#111]
After upgrading from version 1.1.1 to 1.2.0 I encountered a problem. When trying to save model with blank required fields, items of chained selects are not load:
![bug](https://cloud.githubusercontent.com/assets/6038972/12476159/8effcc42-c038-11e5-99b1-3dcb7b479397.png)

With Django 1.9.1 I have same problem, but unable to downgrade for django-smart-selects 1.1.1. Currently no usable version for 1.9.x.

My models:
```python
class Continent(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Country(models.Model):
    continent = models.ForeignKey(Continent)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Location(models.Model):
    continent = models.ForeignKey(Continent)
    country = ChainedForeignKey(
            Country,
            chained_field="continent",
            chained_model_field="continent",
            show_all=False,
            auto_choose=False
    )
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
```
Demo project:
[bug_demonstation.zip](https://github.com/digi604/django-smart-selects/files/98935/bug_demonstation.zip)

**Comment by jimmykobe1171** [comment]
Yes, we knew it and will fix it soon. Thank you.

**Comment by jimmykobe1171** [comment]
fixed and released
