### ISSUE TITLE
this work with uuid? 

### ISSUE THREAD

**Issue by jonaqp** [digi604/django-smart-selects#123]
class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    class Meta:
        abstract = True

class Type(BaseModel):
    name = models.CharField(max_length=50, null=True, blank=True)

class SubType(BaseModel):
    type = models.ForeignKey(Type)
    name = models.CharField(max_length=50, null=True, blank=True)

class Mammal(BaseModel):
    kingdom = models.ForeignKey(Kingdom)
    type = models.ForeignKey(Type)
    subtype = ChainedForeignKey(SubType,chained_field="type",chained_model_field="type", show_all=False,
    )

![captura de pantalla de 2016-03-08 10-31-32](https://cloud.githubusercontent.com/assets/1813636/13606357/abf72420-e519-11e5-9d1b-e263b20f4d97.png)

![captura de pantalla de 2016-03-08 10-36-01](https://cloud.githubusercontent.com/assets/1813636/13606356/abf63f6a-e519-11e5-8d2b-84b9bc5618ac.png)

this work with uuid?

**Comment by jonaqp** [comment]
i fix this 

for a model change the uuid enter the pk json instance does not exist, I have to work with the UUID, which is equal to pk


### utils.py  
need change  pk for id , and convert str for json.dump
`
def serialize_results(results):

    return [
        {'value': str(item.id), 'display': force_text(item)} for item in results
    ]

only work  autofield and uuid django 1.6+



`

**Comment by eulo** [comment]
You should also update ```/smart_selects/widgets.py``` to assign a string instead of an int, to stop the JS throwing errors.

https://github.com/eulo/django-smart-selects/commit/26c83674de01751b65a9c3935379a2b2264af54a

Use: ```pip install git+https://github.com/eulo/django-smart-selects```
If you're database is using UUID for primary keys.

**Comment by SalahAdDin** [comment]
@eulo have you did a PR from your fork to this repository?

**Comment by blag** [comment]
@jonaqp's PR #124 might fix this. The problem with it is that it breaks tests (and therefore possible existing installations).

Is it really necessary to convert `item.id` to a `str`? Or could we special case it if `id` is a UUID?

**Comment by eulo** [comment]
Sorry I'm not sure, I don't know the code base and other use cases.

The fix works for my needs.

**Comment by eulo** [comment]
Converting it to a string allowed the javascript to execute.

It's been running without any issues for me for a while, I suppose you could output and int if you wanted. But I think keeping the type uniform for the JS seems like a better idea.

**Comment by blag** [comment]
I think I fixed this in #186, which is now merged.

I'm preemptively closing this since I intend to cut a new release to PyPI this or next week, but please feel free to reopen it if the `master` branch doesn't work for you.
