### ISSUE TITLE
`django-smart-select` does not take comma separated integers values-multiple selections in parent fields 

### ISSUE THREAD

**Issue by bgarcial** [digi604/django-smart-selects#126]
_This is not issue in reality because is not an error about of some functionality already setup of `django-smart-select`._

_This post, instead of be an issue , is useful for indicate the useful of some functionalities that as a package, `django-smart-select`, could be have available for their users between them I am currently._

# Presenting the situation 

In my current project I want could deploy values based in a previous selection in a field previous. 

_In fact, this is the work  of `django-smart-select` perform, taking data from existing models in the apps._

My situation is that I want that the field parent selection could be of multiple selection and not just  one selection. I share this description about of my challenge, because this, have relation with the `django-smart-select` application can take multiple options in the parent field for deploy values accord to them in the child field. 

My pictures description is the following: 
![Parent and child fields](https://cldup.com/TBrnAhoHYv.png)

Accord to previous image, when select just one option in the parent field I get the `HTTP/1.1" 200` status code

```
[14/Mar/2016 20:52:55] "GET /chaining/filter/medical_encounter_information/Movement/corporal_segment_associated/medical_encounter_information/RehabilitationSession/movement/3/ HTTP/1.1" 200 84
```

In this picture, to illustration effects I show another option selected for indicate the multiple fields more above
![Parent and child fields 2](https://cldup.com/_3Z6dhPbdC.png)

## Selecting two options in the parent field

When I select two options in the parent field (named Segmento Afectado) just are deployed in the child field the options based in the first option that I've selected in the parent field, such as can see in this picture:

![Parent and child fields 2](https://cldup.com/LDrTi0qefs.png) 

In addition when I select more than two options in the parent field such as is showed in the previous figure, in my console, I get the ` HTTP/1.1" 404 Not Found` status code:

```
Not Found: /chaining/filter/medical_encounter_information/Movement/corporal_segment_associated/medical_encounter_information/RehabilitationSession/movement/3,4/
[14/Mar/2016 20:51:27] "GET /chaining/filter/medical_encounter_information/Movement/corporal_segment_associated/medical_encounter_information/RehabilitationSession/movement/3,4/ HTTP/1.1" 404 5432
```

## Identifying the problem and exploring possible solutions

Accord to [this question that I made](http://stackoverflow.com/questions/35778497/how-to-apply-debug-to-the-django-admin-forms-fields/35956203#35956203), I did receive some considerations and support

The challenge lies in the fact in that the application `django-smart-select` don't have an appropriate url pattern to deal with "3,4" block. For this to work, it would need to accept comma-separated integers and then have some kind of parser implemented in the app to filter your results by multiple conditions.

If we detail the [urls.py file of smart select application](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/urls.py#L7), in their regular expressions or `urlpatterns` records does not have implemented that can receive comma separated integer values, currently have this:

```
urlpatterns = [
    url(r'^all/(?P<app>[\w\-]+)/(?P<model>[\w\-]+)/(?P<field>[\w\-]+)/(?P<foreign_key_app_name>[\w\-]+)/(?P<foreign_key_model_name>[\w\-]+)/(?P<foreign_key_field_name>[\w\-]+)/(?P<value>[\w\-]+)/$',
        views.filterchain_all, name='chained_filter_all'),
    url(r'^filter/(?P<app>[\w\-]+)/(?P<model>[\w\-]+)/(?P<field>[\w\-]+)/(?P<foreign_key_app_name>[\w\-]+)/(?P<foreign_key_model_name>[\w\-]+)/(?P<foreign_key_field_name>[\w\-]+)/(?P<value>[\w\-]+)/$',
        views.filterchain, name='chained_filter'),
    url(r'^filter/(?P<app>[\w\-]+)/(?P<model>[\w\-]+)/(?P<manager>[\w\-]+)/(?P<field>[\w\-]+)/(?P<foreign_key_app_name>[\w\-]+)/(?P<foreign_key_model_name>[\w\-]+)/(?P<foreign_key_field_name>[\w\-]+)/(?P<value>[\w\-]+)/$',
        views.filterchain, name='chained_filter'),
]
```

After that I implement the fact of `django-smart-selects` can accept the comma separated integer values as an url, is necessary find some kind of parser implemented in the app to filter my results by multiple conditions when they are selected.

How to can I address this last functionality?
May be modifying to queryset in [some section](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/views.py#L36) some section when the results are filtered when they are product of a models chaining? 

I want can work in this functionality, due to this, I guess than the fisrt thing that I should perform is a project fork, download and begin to analyze my situation with the alternatives that I have been thinked.

Of anyway, I would think that is possible take with some kind of support from you an this community just in case ...

Feeling free of post and write your recommendations about it if you want. 
Best Regards
:smiley:

**Comment by blag** [comment]
This should have been fixed in #139, and that fix has been released to PyPI (version 1.2.4), so I'm closing this. If it's not fixed feel free to reopen. Thank you for explaining it so well!
