### ISSUE TITLE
ChainedManyToManyField don't work with filter_horizontal/filter_vertical

### ISSUE THREAD

**Issue by asduj** [digi604/django-smart-selects#127]
ChainedManyToManyField works excellent in grappelli, but doesn't work if you apply filter_horizontal/filter_vertical on field where you use ChainedManyToManyField

**Comment by blag** [comment]
Can you try using the master branch? This may have been fixed in #148.

**Comment by alalamin25** [comment]
I am using django 1.10 and the filter_horizontal/filter_vertical does not work

**Comment by jorgecorrea** [comment]
I made a little change to solve this problem, in this fork:
https://github.com/jorgecorrea/django-smart-selects
I do not made a pull request because I think that is not the best solution.

**Comment by blag** [comment]
@jorgecorrea If you don't mind, make a PR and I'll see if I can clean it up from there.

**Comment by blag** [comment]
Fixed with #183.
