### ISSUE TITLE
ChainedForeingKey Not working for ManyToManyFields

### ISSUE THREAD

**Issue by Tatoo988** [digi604/django-smart-selects#129]
In Django 1.5 i had this models: 

```python
class Localidad(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    barrio = models.ManyToManyField(Barrio)    
    
    def __unicode__(self):
        return self.nombre
    class Meta:
        verbose_name_plural = "Localidades"
    
class Provincia(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    localidad = models.ManyToManyField(Localidad)
```

and then i wanted to use then as cascade like this: 

```python
class Persona(models.Model):
provincia = models.ForeignKey(Provincia)
    localidad = ChainedForeignKey(Localidad, chained_field = "provincia", chained_model_field = "provincia", auto_choose = True)
```

And everything was ok. Now in Django 1.9 this same code doesn't work: 

```
AttributeError at /chaining/filter/ubicaciones/Localidad/provincia/recursos_de_empresa/Sucursal/localidad/1/
type object 'Localidad' has no attribute 'provincia'
```

Edit (by blag): Fixed code formatting with GFM.

**Comment by sridarm** [comment]
Same error in 1.7 too. Is there any work around to fix this. Any help.

**Comment by SalahAdDin** [comment]
@digi604 What's about this package?

**Comment by blag** [comment]
Why are you using `ChainedForeignKey` instead of `ChainedManyToMany`?

**Comment by blag** [comment]
Closing this, since it sounds like using `ChainedManyToManyField` would solve the issue. Please reopen if you have a reason you're using `ChainedForeignKey`, or if `ChainedManyToManyField` doesn't work for you.
