### ISSUE TITLE
Error when using list_editable

### ISSUE THREAD

**Issue by imaia** [digi604/django-smart-selects#132]
I have a form with list_editable and I get an error on the listing page. This is the error:

> TypeError: fieldComp is null
> if (fieldComp.type === 'text') {

**Comment by blag** [comment]
Need more troubleshooting information. It is absolutely impossible to help you troubleshoot anything with a single error.

* What version of Django?
* Have you tried using the master branch of django-smart-selects?
* What do your models look like?
* Post any other relevant excerpts of files.
