### ISSUE TITLE
Django 1.8 Jquery error 

### ISSUE THREAD

**Issue by IBibik** [digi604/django-smart-selects#134]
I have issue with running on Django 1.8 
I have described my problem at stackovwerflow
http://stackoverflow.com/questions/37081475/django-smart-selects-not-working-correctly-with-my-jquery-settings

**Comment by SalahAdDin** [comment]
Hey, finally, news from this package.

**Comment by blag** [comment]
This might be fixed in f474f47874cda15fb2a58a90473530b81ab73ce5. Can you test and report back?

**Comment by blag** [comment]
You can't place jQuery at the bottom of your page - it has to be placed at the top. This is a current limitation due to how scripts are injected into the document in `widgets.py`. Closing.
