### ISSUE TITLE
Need some setting to completely disabling jQuery script inclusion

### ISSUE THREAD

**Issue by webknjaz** [digi604/django-smart-selects#135]
Hi,

I use `django-bootstrap3`, which inserts jquery script. This package adds its own jquery, which breaks all libraries, binded to the first jquery version (i.e. datepicker etc.)

The way I work around this now:
```python
USE_DJANGO_JQUERY = False
JQUERY_URL = '//about:blank'
```

I would like to avoid such hacking with a single boolean variable

/cc: #134, #117, #85, #59

**Comment by blag** [comment]
Done in f474f47874cda15fb2a58a90473530b81ab73ce5.

```python
JQUERY_URL = False
```

Closing.
