### ISSUE TITLE
Django-smart-selects in admin in inlines doesn't work

### ISSUE THREAD

**Issue by misazr** [digi604/django-smart-selects#140]
I have tried to implement Django-smart-selects with inlines, on that case module doesn't filter objects in drop down list.

Can somebody give me example how to implement this modul with inlines?

What I tried:
models.py

======================================
class Continent(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return "%s" % self.name

class Country(models.Model):
    continent = models.ForeignKey(Continent)
    name = models.CharField(max_length=255)

    def __str__(self):
        return "%s" % self.name

from smart_selects.db_fields import ChainedForeignKey, ChainedManyToManyField, GroupedForeignKey

class VerticalMenuItem(models.Model):
    menu = models.ForeignKey(VerticalMenu)
    title = models.CharField(max_length=50,)
    continent = models.ForeignKey(Continent)
    country = ChainedForeignKey(
        Country,
        chained_field="continent",
        chained_model_field="continent",
        show_all=True,
        auto_choose=True
    )
    url = models.CharField(max_length=40, help_text="Example: '/pages/contact/'")

    def __unicode__(self):
        return self.title
======================================================
admin.py

======================================================
class VerticalMenuItemInline(admin.StackedInline):

    fieldsets = (
        (
            None,
            {
                'fields': ('title_en','title_de', 'url','continent','country',)
            }
        ),
    )

    model = VerticalMenuItem

class VerticalMenuAdmin(TranslationAdmin):
    fields = ['title', 'position', ]
    inlines = [VerticalMenuItemInline, ]
    list_display = ('title','position',)

admin.site.register(VerticalMenu, VerticalMenuAdmin)

**Comment by SalahAdDin** [comment]
Other guy reporting the same error, @digi604, when will you solve this f**g problem?

**Comment by blag** [comment]
Fixed in master with 9b8f0d4a2a8cc9e491f2c590be6ccc189ae07ef6. Closing.
