### ISSUE TITLE
Add Project Maintainer

### ISSUE THREAD

**Issue by halfnibble** [digi604/django-smart-selects#142]
It looks like this project could use another maintainer to look through pull requests and close some of the outdated issues (like support for django==1.3...)

I volunteer myself if you need extra help. 

Thanks,
Josh

**Comment by SalahAdDin** [comment]
@digi604 Can you move this repository to jazzband? 

Many people are waiting for merging many pull request, but you?

**Comment by blag** [comment]
I'm now a GitHub and PyPI maintainer for this, and I'll slowly work my way through issues and PRs, but I'd love help.

@halfnibble: If you're still interested in helping maintain this (which I would sincerely appreciate), email @digi604 directly and give him your GitHub and PyPI usernames.

Closing.

**Comment by SalahAdDin** [comment]
Thanks man!!!
