### ISSUE TITLE
render() got an unexpected keyword argument 'choices'

### ISSUE THREAD

**Issue by 000paradox000** [digi604/django-smart-selects#144]
smart_selects/widgets.py", line 143, in render 

The error is because render method doesn't receive choices parameter. I think this works fine if you comment the choices parameter.

**Original**
output = super(ChainedSelect, self).render(name, value, final_attrs, choices=final_choices)

**Modified**
output = super(ChainedSelect, self).render(name, value, final_attrs)

**Comment by halfnibble** [comment]
Yep. This is fixed in Pull Request #141

**Comment by 000paradox000** [comment]
Thx, this PR should be merged soon :)

**Comment by goutomroy** [comment]
no this not fixed yet.

**Comment by halfnibble** [comment]
I don't know how long is an acceptable wait. I made the PR 12 days ago. But it's summer, and people do take vacations.

If there's no movement in a month or so, I'll make an official fork.

**Comment by 000paradox000** [comment]
+1

**Comment by SalahAdDin** [comment]
Ok man, i'll recommend to @digi604 move this project to jazzband.

**Comment by halfnibble** [comment]
Ok. If I do fork this library, what will I call it? It has to be available on pypi. Looking for suggestions.

**Comment by SalahAdDin** [comment]
@digi604 Man, please, pass this project to jazzband, seems like you haven't time for maintain it!

**Comment by millin** [comment]
@halfnibble, something like django-dinamic-selects or django-dinamic-choices maybe

**Comment by 000paradox000** [comment]
@digi604  pls pass it to jazzband

**Comment by halfnibble** [comment]
What is jazzband?

**Comment by 000paradox000** [comment]
https://jazzband.co/

**Comment by blag** [comment]
I emailed digi604 directly offering to help maintain DSS. 😄

**Comment by marianobrc** [comment]
Hi, was this fix merged to the master brach or to some branch?
I'm sorry I'm not too expert with git, how can I get a version with that fix?

Thanks

**Comment by blag** [comment]
PR #141 (which contains the fix for this) was merged into master. I'm trying to merge a few more PRs before cutting a release to PyPI, but I'm trying to get a new release to PyPI by the end of the week.

You should be able to clone the master branch immediately:

```bash
git clone https://github.com/digi604/django-smart-selects.git
```

or install it with pip directly from master:

```bash
pip install git+https://github.com/digi604/django-smart-selects.git@master
```

And if you wait for the PyPI release, you should be able to upgrade to it:

```bash
pip install --upgrade django-smart-selects
```

**Comment by blag** [comment]
And now that #141 is merged I'm closing this.
