### ISSUE TITLE
Second field wont populate in apache

### ISSUE THREAD

**Issue by ekatsaros** [digi604/django-smart-selects#149]
There is a weird behavior when uploading to apache.
Second field wont populate in template.It works on django development server though but not in apache.
The  {{form.media.js}} is included in block in both cases.

**Comment by millin** [comment]
Did you made direct link to smart_selects path in apache config?

**Comment by millin** [comment]
It should be something like in Apache config:
Alias "/static/smart-selects" "[your_path_to_python_env]/site-packages/smart_selects/static/smart-selects"

**Comment by ekatsaros** [comment]
No i didn't make a link to apache and that was the problem but in the past i count make more than 1 static reference in apache with django.

But what i did collectstatic already and it worked.

Thank you.

**Comment by blag** [comment]
Good to hear you got it working. Thanks @millin!
