### ISSUE TITLE
Console Can't find variable: chainedfk 

### ISSUE THREAD

**Issue by rileywiley** [digi604/django-smart-selects#152]
I have installed smart_selects correctly but the chained selects are not working. I believe the issue lies in that the API is not being accessed because the console gives me an error saying it can't find the var chainedfk. However I am not sure how to debug and fix. Any thoughts?

**Comment by blag** [comment]
Please post excerpts from your problematic `models.py`, the entire traceback (if you have one), any excerpts from your HTML source that contain `<script>` tags, and the entire browser console log.

**Comment by blag** [comment]
You just closed this, so I assume you figured it out. If you need any more help don't be afraid to reopen it or report a different issue.

Also, if you haven't updated to version 1.2.4 (released a few days ago), please do so - it fixed a few issues. 😄 

I should also have more updates coming later this weekend or next week.

**Comment by rileywiley** [comment]
I found #137 and #116. They corrected my issue. Thank you
