### ISSUE TITLE
Problem with IntrospectiveFieldMixin

### ISSUE THREAD

**Issue by 000paradox000** [digi604/django-smart-selects#153]
In db_fields.py self.to_app_name and self.to_model_name is never set

**Comment by blag** [comment]
What's the full traceback from Python?

**Comment by blag** [comment]
Also please post the problematic `models.py` so I can see how you're initializing the `ChainedManyToManyField` or `ChainedForeignKey` you're using.

**Comment by millin** [comment]
@blag problem in code of version 1.2.5. 
self.to_app_name and self.to_model_name always refer to the class itself.

**Comment by 000paradox000** [comment]
We should consider removing contribute_to_class and using mixin in a more clear way. For example in db_fields we can call the parent using super.

Example:

super(ChainedForeignKey, self).__init__(to, **kwargs)

**Comment by 000paradox000** [comment]
This is what i mean https://github.com/000paradox000/django-smart-selects/commit/618e3ad20bd42bfa66eff97f5262945039c48e34

**Comment by blag** [comment]
I think have fixed this is master. Can you test that please?

Part of the problem was not using `super()`.

**Comment by millin** [comment]
@blag Now it works fine for non-recursive model.
I can't check for recursive, because I have no recursive model, sorry.

**Comment by blag** [comment]
@millin Thanks for testing!

**Comment by 000paradox000** [comment]
It works perfect for me now thanks a lot @blag   @millin
