### ISSUE TITLE
Using wrong model?

### ISSUE THREAD

**Issue by adam-tokarski** [digi604/django-smart-selects#157]
Hi,
please tell me what I'm doing wrong as I'm trying to use this awesome library in one of my project and have issue.
I'm running on Django 1.10 with django-rest-framework 3.5 (Python 3.5), and I have something like this:
```python
class Company(models.Model):
    name = models.CharField(max_length=255)

class Category(models.Model):
    company = models.ForeignKey(Company)

class Project(models.Model):
    company = models.ForeignKey(Company)
    category = ChainedForeignKey(
        to=Category,
        chained_field="company",
        chained_model_field="company"
    )

```

This is something I want to use on Admin Form, in Project view.

The problem is, that Category shows all Projects, instead of Categories filtered by Companies. As I've took a look, there is because widget get model name from meta which is `Project`. 

Is there any possiblity to control this? Or did I just misused this somehow?

Thanks in advance!

The admin part is:
```python
@register(Project)
class ProjectAdmin(ModelAdmin):
    fieldsets = (
        (None, {
            'fields': (
                ('company',),
                ('category',),
            )
        }),

    )
```

**Comment by scream4ik** [comment]
Same problem with latest version (1.2.5 from pypi). With 1.2.4 all fine

**Comment by adam-tokarski** [comment]
Thanks for tip, I'll try it out.

**Comment by adam-tokarski** [comment]
Ok, downgrading version worked! Thanks again!

The problem is now that when I have some self-reference, like 
```python
  parent_smth = ChainedForeignKey(
        'self',
        chained_field="company",
        chained_model_field="company"
    )
```
there is error:
```
on django_smart_selects-1.2.4-py3.5.egg/smart_selects/db_fields.py", line 157, in __init__: 
self.to_app_name, self.to_model_name = to.split('.')
ValueError: not enough values to unpack (expected 2, got 1)
```

I've got to use `app.smth` instead of `self`.

**Comment by blag** [comment]
Can you check out if this issue still happens on the `master` branch (test with both `app.smth` and `self`? I think I fixed that issue there, I've just been waiting to push it to PyPI.

**Comment by blag** [comment]
I pushed the code in `master` out to PyPI, so can you try upgrading to version 1.2.6 and see if you still get this error?

**Comment by scream4ik** [comment]
Now for me all fine.
@adam-tokarski confirm please

**Comment by adam-tokarski** [comment]
Seems to be working now! Thanks!
I've used the newest version from PyPI.
