### ISSUE TITLE
Smart selects 1.2.5 empty response

### ISSUE THREAD

**Issue by quevon24** [digi604/django-smart-selects#158]
I just want to report that 1.2.5 it's not returning any response, it makes the post fine, but json response is always [ ]

Version 1.2.4 works fine.

**Comment by lx1054331851** [comment]
smart selects 1.2.6 work fine in `master`, but it has not being pushed to PyPi.

**Comment by blag** [comment]
Actually I pushed 1.2.6 in `master` to PyPI a few hours ago.

@quevon24 Please upgrade to that and report back if you're still experiencing this issue.

**Comment by quevon24** [comment]
Thanks, I am using the PyPI, I'll check it and report it back.

**Comment by quevon24** [comment]
It works great, thanks for fix it and upload it to PyPI.

**Comment by blag** [comment]
No worries! Closing.
