### ISSUE TITLE
ChainedManyToManyField on Admin site - missing selected

### ISSUE THREAD

**Issue by adam-tokarski** [digi604/django-smart-selects#161]
There is issue that `ChainedManyToManyField` doesn't highlight selected options, when rendered on admin site.

When some options are selected and it's saved, after reload chained M2M field is without any selections. 
The parent is classic `Foreign Key`. 

I've already addressed it [here](https://github.com/digi604/django-smart-selects/pull/160).

**Comment by blag** [comment]
Since #160 is merged I'm just gonna close this. Thanks!
