### ISSUE TITLE
Displaying the selected option problem in safari browser 

### ISSUE THREAD

**Issue by erdemlal** [digi604/django-smart-selects#162]
When i saved a model and want to see it, chained select contains two options that have selected attribute in the created html, this causes Safari browser to display the first option with selected attribute which is the default empty option, but actually i want to see the other one. I tested it with chrome and ie and they are working but safari doesn't show the correct option.
![capture](https://cloud.githubusercontent.com/assets/1925331/20176966/067b8b9c-a753-11e6-8e48-5f3d518b5c19.PNG)

**Comment by applecat** [comment]
I have the same issue too. I fix this in two commits above. Tested in Safari, Chrome, FF — everything is ok now. @digi604, please merge. )

**Comment by blag** [comment]
Hi, I'm maintaining this project now. I apparently missed this, sorry about that. I've cherry picked those commits to `master`, and they are passing.

I might merge a few others from #167, then I'll push out a new update to PyPI tonight or tomorrow. Thanks for the fix @applecat! 💙 

Closing.

**Comment by blag** [comment]
I pushed version 1.2.7 to PyPI, please test it and report back if this issue isn't fixed. Thanks! 😄
