### ISSUE TITLE
it doesn't work with select2 js.

### ISSUE THREAD

**Issue by medbenmakhlouf** [digi604/django-smart-selects#166]
Hi, 

I am trying to use django-smart-selects with select-2 js plugin. so is there any way to use the current one with select2 plugins ?

thanks

**Comment by blag** [comment]
It should be possible, but the current code does not use the select2 javascript plugin - you'll have to code that yourself. Please submit a PR with your changes if you do.

Is there some functionality you'd like that the current code doesn't do?

**Comment by SalahAdDin** [comment]
@blag This is a very bad problem, because i saw `django-jet` works with `select2` library.

**Comment by medbenmakhlouf** [comment]
@blag , it works fine for me after add I copy paste the same js code:
`            $('#id_category_level_1').change(function (e) {
                // mostly used event, fired to the original element when the value changes
                var url = "/chaining/filter/interests/CategoryLevel2/category_level_1/invites/Invite/category_level_2";
                chainedfk.init('#' + this.id, url, "#id_category_level_2", undefined, "None Selected", false);
            });
            $('#id_category_level_2').change(function (e) {
                // mostly used event, fired to the original element when the value changes
                var url = "/chaining/filter/interests/CategoryLevel3/category_level_2/invites/Invite/category_level_3";
                var initial_parent = $('#' + this.id).val();
                chainedm2m.fill_field(e.val, null, '#id_category_level_3', url, initial_parent, false);
            });
`

**Comment by blag** [comment]
@SalahAdDin As far as I'm aware, it doesn't stop you from using django-smart-selects with django-jet. This project simply doesn't utilize the select2 library that is utilized by django-jet. I see no problem here. If this is such a big problem for you, I'm happy to accept pull requests! 😄 

@medbenmakhlouf I couldn't read the code you posted, so I reformatted it with [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/). If you can solve the problem you are having in a more generic fashion, please submit a pull request for this project so others may use your fixed code. Thanks! 😄

**Comment by blag** [comment]
Closing, since a workaround for this issue is possible.

**Comment by NorDULaN** [comment]
A simple way to solve this problem:
insert static smart-selects at the end of the base.html
It helped me in the custom admin panel with select2
