### ISSUE TITLE
ChainedForeignKey and ChainedManyToManyField fields don't work together.

### ISSUE THREAD

**Issue by medbenmakhlouf** [digi604/django-smart-selects#167]
Hi, 
I am trying to use ChainedForeignKey and ChainedManyToManyField fields in the same model and both fields are related.

here is my case : 
- I am having 3 models category level 1, category level 2, category level 3 and all of them are related.
<img width="845" alt="screen shot 2017-01-01 at 11 45 08 pm" src="https://cloud.githubusercontent.com/assets/13701406/21583322/6fafe23c-d07c-11e6-88c9-ef9b0d6b485e.png">

then I am trying to use Chained fields in other model like this : 
<img width="818" alt="screen shot 2017-01-01 at 11 47 41 pm" src="https://cloud.githubusercontent.com/assets/13701406/21583331/ca38fa2c-d07c-11e6-9420-d1bf2f8e8c24.png">

the smart select works fine with me when I am in Create View. here is the screen shots : 
<img width="441" alt="screen shot 2017-01-01 at 11 50 06 pm" src="https://cloud.githubusercontent.com/assets/13701406/21583342/201a5fe4-d07d-11e6-94db-549e79b0e41a.png">

then when I back to edit mode , I will lose **my selected** ChainedManyToManyField:
<img width="437" alt="screen shot 2017-01-01 at 11 53 25 pm" src="https://cloud.githubusercontent.com/assets/13701406/21583357/844a66b2-d07d-11e6-8a5e-53fdf2ce9fff.png">

I was able to figure out the solution when I change the condition value in **chainm2m.js** like this : 
<img width="822" alt="screen shot 2017-01-01 at 11 35 28 pm" src="https://cloud.githubusercontent.com/assets/13701406/21583369/e862993a-d07d-11e6-9c7c-ffef4c5975e6.png">

then it works fine for me. am I doing something wrong or that really need a hotfix ? Thanks

**Comment by blag** [comment]
@medbenmakhlouf Sorry, I don't understand your markup - can you post a diff or post the final version of that section of code?

If you enclose your diff [like this](https://stackoverflow.com/a/40883538/6461688):

    ```diff
    // vvv diff output vvv
    public class Hello1
    {
       public static void Main()
       {
    -      System.Console.WriteLine("Hello, World!");
    +      System.Console.WriteLine("Rock all night long!");
       }
    }
    // ^^^^ diff output ^^^^
    ```

GitHub will render it like this:

```diff
// vvvv diff output vvvv
public class Hello1
{
   public static void Main()
   {
-      System.Console.WriteLine("Hello, World!");
+      System.Console.WriteLine("Rock all night long!");
   }
}
// ^^^^ diff output ^^^^
```

and that makes it easier for me to see what your changes are.

I'll push out a hotfix to PyPI for this if the tests pass with your changes.

**Comment by blag** [comment]
I pushed version 1.2.7 to PyPI, please test it and report back if this issue isn't fixed. Thanks! 😄

**Comment by medbenmakhlouf** [comment]
@blag, thank you :) . I will test it and let you know.

**Comment by blag** [comment]
@medbenmakhlouf How did your testing go?

**Comment by medbenmakhlouf** [comment]
@blag , for right now, it is fine. I have been using it from a while and didn't notice any issue. so, I think it should be good.
