### ISSUE TITLE
Doesn't work with raw_id_fields

### ISSUE THREAD

**Issue by zatan** [digi604/django-smart-selects#169]

**Comment by blag** [comment]
Please provide:

* An explanation of what is happening
* An explanation of what you expected
* Any debugging/troubleshooting information, like a traceback or any steps you have taken to try to resolve the problem on your own
* The relevant `models.py`, `forms.py`, `admin.py` and any other relevant files that that are problematic for you.

**Comment by blag** [comment]
I took a look at the Django documentation for `raw_id_fields`, and I don't understand how you think this should work, and you haven't given me any more information after prompting, so I'm closing this. Feel free to reopen with more information.
