### ISSUE TITLE
ChainedForeignKey select options are appended without first emptying/replacing

### ISSUE THREAD

**Issue by carn1x** [digi604/django-smart-selects#175]
## Steps to reproduce

1. Upgrade from 1.2.2 to 1.3.1
2. Use ChainedForeignKey field

## Expected behavior

1. Changing the value of the chained_model_field form field will replace all options in the ChainedForeignKey form field with those desired.

## Actual behavior

1. Changing the value of the chained_model_field form field appends all options in the ChainedForeignKey form field, leaving all existing options.

Analysis of https://github.com/digi604/django-smart-selects/blob/master/smart_selects/static/smart-selects/admin/js/chainedfk.js indicates that the JS is only replaces the `<select>` HTML when `!val || val === ''` :
https://github.com/digi604/django-smart-selects/blob/master/smart_selects/static/smart-selects/admin/js/chainedfk.js#L34

Previous versions however would override the `<select>` HTML without condition within the `getJSON()` handler:
https://github.com/digi604/django-smart-selects/blob/1.2.2/smart_selects/static/smart-selects/admin/js/chainedfk.js#L43

**Comment by rooterkyberian** [comment]
Seems recent  security fix ( 52bc3b0620a742a6a5293a230735f3c9d462f3a9 ) is at fault here as it only appends new options when before they were replaced all at once.

**Comment by rooterkyberian** [comment]
Pull request with fix: https://github.com/digi604/django-smart-selects/pull/176

**Comment by blag** [comment]
Fix released to PyPI as version 1.3.2.

@carn1x Thanks for reporting.

@rooterkyberian Thanks for the fix!
