### ISSUE TITLE
Chained Selects is not working

### ISSUE THREAD

**Issue by wmartinez79** [digi604/django-smart-selects#18]
Hi, I'm newbie with Django and I was looking for an example of how to implement a validation to show cities from a selected country, I found your example and it looks pretty cool and easy, unfortunately I'm sure I did something wrong but I am not able to see it, I followed the readme example but it doesn't work, it didn't show anything. Using the runserver script I can see this line, but I'm not sure how debug it 

[02/May/2011 18:42:00] "GET /chaining/filter/catalogos/Departamento/pais/1/ HTTP/1.1" 500 82076

 Would you please help me? I'm trying to implemented in the model "Municipio", this model has to be chained to "Departamento" model,  below are my files:

`models.py`

```python
from django.db import models
from sicfi.smart_selects.db_fields import ChainedForeignKey

...

class Municipio(models.Model):
    nombre = models.CharField(max_length = 64)
    pais   = models.ForeignKey(Pais)
    departamento = ChainedForeignKey(
        Departamento,
        chained_field="pais",
        chained_model_field="pais",
        show_all=False,
        auto_choose=True
    )
    estado = models.ForeignKey(Estado)
```

`forms.py`

```python
from django import forms
from django.forms import ModelForm

...

class MunicipioForm(ModelForm):

    class Meta:
            model = Municipio
```

`urls.py`

```python
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *
from django.conf import settings

...

urlpatterns = patterns('',
    (r'^$', 'sicfi.views.index'),
    (r'^catalogos/', include('sicfi.catalogos.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
```

`settings.py`

```python
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.flatpages',
    'django.contrib.markup',
    # Uncomment the next line to enable the admin:
     'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    # 'django.contrib.admindocs',
)+apps.SICFI_APPS
```

`apps.py`

```python
SICFI_APPS = (
    'sicfi.catalogos',
    'sicfi.usuarios',
    'sicfi.smart_selects'
)
```

Edit (by blag): Updated to use GFM.

**Comment by SalahAdDin** [comment]
Could you solve this issue?

**Comment by blag** [comment]
Did you import `apps` in your `settings.py`?

And I'm going to close this because it's been 5 years since the last update (from the reporter). Feel free to reopen if it's still relevant to you.
