### ISSUE TITLE
Exception Value: need more than 1 value to unpack

### ISSUE THREAD

**Issue by CombatCode** [digi604/django-smart-selects#19]
Hello, i have a some stange issue:

Django Version:     1.3
Exception Type:     ValueError
Exception Value:    need more than 1 value to unpack
Exception Location:     /home/combatcode/www/somehere/smart_selects/db_fields.py in **init**, line 16
Python Executable:  /usr/local/python2.6/bin/python
Python Version:     2.6.1

Model:

``` python
class Somemodel(models.Model):
    kategoriagl = models.ForeignKey('self')
    kategorianext = ChainedForeignKey(
        'self', 
        chained_field="kategoriagl",
        chained_model_field="kategoriagl", 
        show_all=False, 
        auto_choose=True
    )
```

app is installed, and imported to models. Can u tell me what is wrong?

Edit (by blag): Updated to use GFM.

**Comment by blag** [comment]
This is a bug - `ChainedForeignKey` expects a module string of the format "<module>.<model>".

The current workaround is to specify the target as a full string. Example:

```python
class Somemodel(models.Model):
    kategoriagl = models.ForeignKey('self')
    kategorianext = ChainedForeignKey(
        'somemodule.Somemodel',  # <-- "module.Model"
        chained_field="kategoriagl",
        chained_model_field="kategoriagl", 
        show_all=False, 
        auto_choose=True
    )
```

You aren't the only person who reported this issue. I'll look into fixing it.

**Comment by SalahAdDin** [comment]
Interesting, please update the documentation.

**Comment by blag** [comment]
This was fixed in 15d3d6e52684feaa666eadf988e0ea9b878c4297 and released to PyPI a few days ago. Please update to 1.2.6 (or later).

@SalahAdDin I don't think any additional documentation is required for this, since it's really just re-enabling built-in behavior of vanilla Django `ForeignKey` and `ManyToManyField` relations. But if you have any suggestions for additional documentation I'd be happy to work on that.

**Comment by SalahAdDin** [comment]
@blag Release it in pypi or here in github, in release section we can see until 1.2.2.

**Comment by blag** [comment]
@SalahAdDin https://pypi.python.org/pypi?:action=display&name=django-smart-selects&version=1.2.6
