### ISSUE TITLE
Not working with checkboxmultipleselect widget

### ISSUE THREAD

**Issue by toweralaka** [digi604/django-smart-selects#190]
chained m2m breaks when checkboxmultipleselect widget is introduced

**Comment by blag** [comment]
Fill out the issues template please. It's next to impossible to solve these issues with short descriptions like "breaks".

Closing until you fill out the template.

**Comment by blag** [comment]
Template is here: https://github.com/digi604/django-smart-selects/blob/master/.github/ISSUE_TEMPLATE.md
