### ISSUE TITLE
Error with add new Inline form

### ISSUE THREAD

**Issue by ballbrk** [digi604/django-smart-selects#193]
All versions of django-smart-selects prior to version 1.2.8 are vulnerable to an XSS attack as detailed in [issue 171](https://github.com/digi604/django-smart-selects/issues/171#issuecomment-276774103). As a result, all previous versions have been removed from PyPI to prevent users from installing insecure versions. All users are urged to upgrade as soon as possible.

## Checklist

- [ x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure.
- [x ] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] I have debugged the issue to the smart_selects app.
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.

## Steps to reproduce

Hi,
I've this Inline

class EstateQualityEstateInline(admin.StackedInline):
model = EstateQualityEstate
extra = 2
suit_classes = 'suit-tab suit-tab-quality'

class EstateQualityEstate(models.Model):
estate = models.ForeignKey(Estate)
estate_quality = models.ForeignKey(EstateQuality, related_name='estate_quality_estate')
estate_quality_options = ChainedForeignKey(
EstateQualityOptions,
chained_field="estate_quality",
chained_model_field="estate_quality",
show_all=False,
auto_choose=True,
related_name='estate_quality_options_estate'

)
The code selects works fine for the two inline forms created. But when I click on "Add new form" in the inline. The new form don't populate the chained field.

**Comment by blag** [comment]
Okay, this still doesn't tell me what's going on. Open up your browser developers tools and post the AJAX request data and the AJAX response data. Thanks!

**Comment by ballbrk** [comment]
Hi the problem that the new form don’t send request

**Comment by blag** [comment]
Does your browser console show anything?

**Comment by ballbrk** [comment]
No,  the new one don’t send request

**Comment by blag** [comment]
Post the entire HTML file please.

**Comment by blag** [comment]
Just post everything that could possibly be relevant - I don't like guessing without any useful information. This includes:

* Your `INSTALLED_APPS` setting
* HTML of page that isn't working
* Relevant excerpts from `forms.py`, `views.py`
* Browser request/responses, even if they're empty (the endpoints may give me some clues)
* Any troubleshooting steps you have taken so far

Also, try disabling django-suit and see if that fixes it.

**Comment by ballbrk** [comment]
I test it with and without django-suit



OTHER_APPS = [
    'analytical',
    'schedule',
    'djangobower',
    'adminsortable2',
    'multiupload',
    'easy_thumbnails',
    'modeltranslation',
    'easy_thumbnails.optimize',
    'ckeditor',
    'smart_selects',
    'cachalot',
    'cities_light',
    'compressor',
    'raven.contrib.django.raven_compat',
    'djangoseo',
    'djmoney',
    'django_comments',
    'polymorphic',
    'import_export',
    'django_extensions',
    'filer',
    'mptt',
    'tagging',
    'reversion',
    'phonenumber_field',
    'location_field.apps.DefaultConfig'

    ]
DJANGO_APPS = [

    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',
    'django.contrib.flatpages',
    'django.contrib.sites',
    'django.contrib.gis',
'django.contrib.admindocs'
]
LOCAL_APPS = ['account',
              #'zinnia',
               'common',
               'estate',
               'location',
               'customer',
               'rental'
               ]
INSTALLED_APPS = OTHER_APPS + DJANGO_APPS + LOCAL_APPS

Browser request/responses, even if they're empty : 


request URL:http://127.0.0.1:8000/chaining/filter/estate/EstateQualityOptions/estate_quality/estate/EstateQualityEstate/estate_quality_options/4/
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:8000
Response Headers
view source
Cache-Control:no-cache, no-store, must-revalidate, max-age=0
Content-Type:application/json
Date:Thu, 23 Mar 2017 21:52:12 GMT
Expires:Thu, 23 Mar 2017 21:52:12 GMT
Last-Modified:Thu, 23 Mar 2017 21:52:12 GMT
Server:WSGIServer/0.1 Python/2.7.13
X-Frame-Options:SAMEORIGIN
Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:es,pt-BR;q=0.8,pt;q=0.6,en-US;q=0.4,en;q=0.2,ca;q=0.2
Connection:keep-alive
Cookie:djdt=hide; sessionid=wu5miwf64r9qvig9xlkqebmqiu3yuul4; csrftoken=qQKsD447ZmWN5Jh8w0LTA7OixWU7ZoxvTxvCN4xHOuIOiY5R0mdqKm1r0h5Jv2U3
DNT:1
Host:127.0.0.1:8000
Referer:http://127.0.0.1:8000/admin/estate/estate/add/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36
X-Requested-With:XMLHttpRequest

Response:
[{"display": "A la Calle", "value": 50}, {"display": "A la piscina", "value": 53}, {"display": "A la Playa", "value": 44}, {"display": "Al golf", "value": 56}, {"display": "Al Mar", "value": 42}, {"display": "Al Parque", "value": 45}, {"display": "Al Puerto", "value": 51}, {"display": "Avenida", "value": 48}, {"display": "Centro Comercial", "value": 52}, {"display": "Colegio", "value": 54}, {"display": "Exterior", "value": 46}, {"display": "Jard\u00edn", "value": 49}, {"display": "Monta\u00f1a", "value": 43}, {"display": "Patio", "value": 47}, {"display": "Plaza", "value": 55}]

This request is the request/response created by the form.
When I click "Add Estate Quality Estate". The new inline model don't make any request/response


[html.txt](https://github.com/digi604/django-smart-selects/files/866304/html.txt)

**Comment by blag** [comment]
This isn't supported yet. It relies on a refactor that externalizes the Javascript and updates the way we select widgets to attach event handlers to.

I'm keeping this open and adding the new "Needs external javascript rewrite" tag.

**Comment by blag** [comment]
I also don't have too much time to work on the rewrite, but I can review a pull request for it. So if you find the time, please submit a PR. Thanks! 😄

**Comment by vborras** [comment]
Hi @blag,

I'm having the same issue: chained fields don't get updated for new forms and won't even make a request, but they do in existing forms and extras. I've been reading through all the issues and i'm a little confused, as I thought it was solved with #148, but now I read this issue and you say it isn't supported yet. Maybe there's a difference I can't see?

I'm using 1.3.4 with Django 1.10 and Suit, if you need any further information or want me to open a new issue just let me know, but I think my case is very similar to this.

**Comment by blag** [comment]
@vborras Good question; they are different. #148 was about supporting modifying existing inlines, this one is about adding new objects via inlines. So if I have a parent with two children that **already** exist, D-S-S should support modifying the children (that's what #148 is about). This issue is about **adding a new** child via an inline, which isn't supported yet.

And IIRC, this is because the `id` attributes of the `<input>`s are known for existing objects, but not known for new `<input>`s that are created dynamically. That and we currently write out inline, customized javascript for each individual widget. A side effect of externalizing our JS is that we have to identify all `<input>`s we want D-S-S to bind to by their `class` attributes, which would make it much easier to support this. That is the "proper" way to do what we want, after all.

I hope that makes sense. Feel free to ask more questions if it isn't. And if you're having the same issue - unable to *add new* objects via inlines - please post any helpful info in this issue (and don't create a duplicate). If you are having a different issue that hasn't been reported yet, then please open a new issue. Thanks!

**Comment by vborras** [comment]
I see the problem. I'm not very confident about my JS skills, but I need this functionality, so I'll give it a try and if I get to a solution, I'll make a PR. Any guidelines on how to face this? I'm thinking about using data attributes instead of classes, is that ok?

**Comment by blag** [comment]
This should be fixed in version 1.4.0, so I'm closing this. If it's not fixed please reopen it.

**Comment by nameisnot** [comment]
I am facing the same issue on smart-selects 1.5.4 / Django 2.0.6 / Py 3.6 (see https://github.com/digi604/django-smart-selects/issues/276).

Is the issue sorted out yet?

**Comment by pakibuy2020** [comment]
Hi Is this issue has been resolved already? I'm using the latest version both django and django-smart-selects

**Comment by drakedracosupa** [comment]
Hi! Has this issue been resolved yet? I'm also using the latest versions of both django and django-smart-selects and I'm still facing the same issue.

**Comment by KaktusOnFire** [comment]
@blag hi!

this problem is still relevant for versions above 1.5.4.

Log from latest (1.6.0) version when i changed parent chained field:
```
2023-06-13 17:44:36 | INFO/MainProcess | "GET /chaining/filter/crm/Tariff/product_group/crm/UserInvoiceItem/tariff/53/ HTTP/1.1" 200 364
2023-06-13 17:44:36 | INFO/MainProcess | "GET /chaining/filter/crm/Product/product_group/crm/UserInvoiceItem/product/53/ HTTP/1.1" 200 556
```

Log from version 1.5.4 in same situation:
```
2023-06-13 17:57:36 | INFO/MainProcess | "GET /chaining/filter/crm/Tariff/product_group/crm/UserInvoiceItem/tariff/50/ HTTP/1.1" 200 361
2023-06-13 17:57:36 | INFO/MainProcess | "GET /chaining/filter/crm/Product/product_group/crm/UserInvoiceItem/product/50/ HTTP/1.1" 200 552
2023-06-13 17:57:36 | INFO/MainProcess | "GET /chaining/filter/crm/Discount/product_groups/crm/UserInvoiceItem/discounts/50/ HTTP/1.1" 200 129
```



My model structure:
```
product_group = models.ForeignKey(ProductGroup, on_delete=models.RESTRICT, default=None, null=True)

  product = ChainedForeignKey(Product,
                              chained_field="product_group",
                              chained_model_field="product_group",
                              show_all=False,
                              auto_choose=True,
                              sort=True,
                              default=None
                              )
  tariff = ChainedForeignKey("Tariff",
                             chained_field="product_group",
                             chained_model_field="product_group",
                             show_all=False,
                             auto_choose=True,
                             sort=True,
                             default=None
                             )
  discounts = ChainedManyToManyField("Discount",
                                     horizontal=True,
                                     chained_field="product_group",
                                     chained_model_field="product_groups",
                                     default=None,
                                     blank=True,
                                     )
```

I think its something wrong with inlines in versions >1.5.4
