### ISSUE TITLE
Javascript in Widget should alias the jQuery name space

### ISSUE THREAD

**Issue by fatbox** [digi604/django-smart-selects#2]
The onload function should be invoked as
`jQuery(document).ready(function($) {`

This ensures it works when jQuery is being used by other things, such as Grappelli.

**Comment by blag** [comment]
What file exactly do you want to change?

**Comment by blag** [comment]
Given the age of this issue, and the fact that I can see anything wrong with what we're currently doing, I think this was solved awhile back. Closing, but feel free to reopen if you have any specific suggestions. Thanks!
