### ISSUE TITLE
Leaking data security potential risk

### ISSUE THREAD

**Issue by ng-celes** [digi604/django-smart-selects#201]
## Checklist

<sup><sup>Put an `x` in the bracket when you have completed each task, like this: `[x]`</sup></sup>

- [x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [x] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] I have debugged the issue to the `smart_selects` app.
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Steps to reproduce

While browsing page using django-smart-selects put in address bar something similar to: http://127.0.0.1:8000/chaining/filter/auth/User/is_superuser/auth/User/password/1/

## Actual behavior

Returned data contains existing usernames

## Expected behavior

Models not containing fields from django-smart-selects app shouldn't be queried.

**Comment by blag** [comment]
Working on this...
