### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by jacktrades** [digi604/django-smart-selects#203]
I sent an email to @digi604 but it appears that he doesn't maintain this project anymore.  @blag please email me nick(at)frez.me regarding a potential security vulnerability.

Side note: It would be nice to have a contact point for security issues in the readme.

----------------

- [x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [x] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have debugged the issue to the `smart_selects` app.
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Steps to reproduce

1. 
2. 
3.

**Comment by blag** [comment]
Thank you for reporting this issue. I will resolve this outside of GitHub, so I'm going to close this.
