### ISSUE TITLE
README settings don't match code

### ISSUE THREAD

**Issue by davmlaw** [digi604/django-smart-selects#220]
## Checklist

- [X ] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [ X] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] I have debugged the issue to the `smart_selects` app.
- [ X] I have reduced the issue to the simplest possible case.
- [ ] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Actual behavior

Readme.md says the settings are:

`SMART_SELECTS_JQUERY_URL
SMART_SELECTS_USE_DJANGO_JQUERY
`

Code settings are:

`USE_DJANGO_JQUERY = getattr(settings, 'USE_DJANGO_JQUERY', False)
JQUERY_URL = getattr(settings, 'JQUERY_URL', 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js')
`

## Expected behavior

Code and README match

**Comment by blag** [comment]
Fixed. Thanks!
