### ISSUE TITLE
Change form output

### ISSUE THREAD

**Issue by ekatsaros** [digi604/django-smart-selects#234]
Hi 
Is there a way to change the form output html?
I am trying to change select with option to ul and li cause some options have large text that go offscreen due to option tag cannot be styled.
I tried to change it in chainedfk.js file but it doesnt seem to work as depended menu is not displayed.
I tried also with crispy forms but i get following error.

Exception Type: 	StopIteration
Exception Location: 	/.../..../widgets.py in render, line 98

Any ideas?

Thank you

**Comment by blag** [comment]
You can render the form itself manually: https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html

but changing just the smart selects field is not supported right now.
