### ISSUE TITLE
More options to filter the chained field

### ISSUE THREAD

**Issue by fuatu** [digi604/django-smart-selects#243]
This is a feature request:

## Actual behavior
For chained fields it displays all the lines from database. 

## Expected behavior
For chained fields it will be very nice to be able to filter further. 
For example I am getting a list of debts for a user. So when the user is selected I can select relevant debts in the select dropdown. 
However when the debt is paid I have a field paid = True. So I want to display only records where it is relevant to selected user and paid = False.

**Comment by blag** [comment]
If you need more complex filtering, etc., I would recommend the django-autocomplete-light package.

This is meant to be a "quick and dirty" app to get you up and running, but more complex functionality (including more security!) is possible in DAL.

I'm also a little bit worried that you are exposing sensitive user information via this app's AJAX endpoints. Be aware that the AJAX endpoints do not enforce any permissions, and allow anybody in the world to query models with a chained field.

Closing.
