### ISSUE TITLE
Verbose name of the ChainedManyToManyField not working in newer versions

### ISSUE THREAD

**Issue by OndraRehounek** [digi604/django-smart-selects#252]
You **MUST** use this template when reporting issues. Please make sure you follow the checklist and fill in all of the information sections below.

----------------

All versions of django-smart-selects prior to version 1.2.8 are vulnerable to an XSS attack as detailed in [issue 171](https://github.com/digi604/django-smart-selects/issues/171#issuecomment-276774103). As a result, all previous versions have been removed from PyPI to prevent users from installing insecure versions. All users are urged to upgrade as soon as possible.

## Checklist

<sup><sup>Put an `x` in the bracket when you have completed each task, like this: `[x]`</sup></sup>

- [x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [x] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have debugged the issue to the `smart_selects` app.
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Steps to reproduce

1. Set verbose_name for ChainedManyToManyField (with ugettext or without)

## Actual behavior
The verbose name is not used for form laberl, it shows database name of the field instead. It does work correctly for ChainedForeignKey fields. It worked with older versions (1.2.9) but after we upgraded to 1.5.3, we are experiencing quite many difficulties. It is wrong already in the __init__() of the form.

## Expected behavior
The field label is set according to given verbose name.
```
city = ChainedManyToManyField(City, verbose_name=_(u'Město'), chained_field='district', chained_model_field='district', auto_choose=True, blank=True)
```

**Comment by blag** [comment]
Please try out the `pass-verbose-name-through` branch for me and tell me if this is fixed. Thanks!

**Comment by OndraRehounek** [comment]
Works perfectly, thank you for such a fast fix!

**Comment by blag** [comment]
Merged into `master` will push out a release to PyPI soon.

**Comment by blag** [comment]
I cut a release to PyPI and GitHub as version `1.5.4`. Thanks!

**Comment by blag** [comment]
Sorry, was on a plane with spotty internet when I wrote that. The upload to PyPI didn't work then. I have just now successfully uploaded version 1.5.4 to PyPI:

https://pypi.python.org/pypi/django-smart-selects
