### ISSUE TITLE
Doesn't Apear chained_field value 

### ISSUE THREAD

**Issue by bassamghouzi** [digi604/django-smart-selects#256]
## Actual behavior

1- I Install Djnago Smart Selects by this commend `pip install django-smart-selects`

2- Added in settings => installed_apps + Add JQuery Permission line : 
`INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MyApp',
    'smart_selects',
]
USE_DJANGO_JQUERY = True`

3-  models.py  :

`class Topic(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=400)
    image = models.FileField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now=True)

class Reply(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    reply = models.TextField()
    created_date = models.DateTimeField(auto_now=True)

class Likes(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True)
    reply = ChainedForeignKey(
        Reply,
        chained_field="topic",
        chained_model_field="topic",
        show_all=False,
        auto_choose=True)` 

4- admin.py : 
`class LikesAdmin(admin.ModelAdmin):
admin.site.register(models.Likes, LikesAdmin)`

5- urls : 
`urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^my-app/', include('MyApp.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
]`

Result : `Reply`'s field keep empty after selecting `Topic` field
Not working either in admin panel and templates 

Did I Miss Any thing  ?

**Comment by bassamghouzi** [comment]
Any Reply ?

**Comment by GrilloLuca** [comment]
Can you please check if you have some error in the browser's console?

**Comment by bassamghouzi** [comment]
@GrilloLuca Yes, There is 

> bindfields.js:12

> Uncaught ReferenceError: chainedfk is not defined
>     at initItem (bindfields.js:12)
>     at HTMLSelectElement.<anonymous> (bindfields.js:31)
>     at Function.each (jquery.min.js:2)
>     at HTMLDocument.<anonymous> (bindfields.js:30)
>     at i (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at Function.ready (jquery.min.js:2)
>     at HTMLDocument.J (jquery.min.js:2)

**Comment by GrilloLuca** [comment]
check this issue: https://github.com/digi604/django-smart-selects/issues/253
Solution: RafaDias/django-smart-selects@61f182f

**Comment by bassamghouzi** [comment]
That worked 
I Hope Disruption Update as soon as possible 
thx @GrilloLuca
