### ISSUE TITLE
dismissAddAnotherPopup is undefined

### ISSUE THREAD

**Issue by yunmanger1** [digi604/django-smart-selects#26]
Hi! Sometimes for some reason I get an error 'dismissAddAnotherPopup is undefined', when I am using smart-select on client site.

This condition solves the problem. https://github.com/yunmanger1/django-smart-selects/commit/8168c80112679188e489924aa5a9d35dc20dd249#L0L130

**Comment by SalahAdDin** [comment]
Are fix now this bug with the last release?

**Comment by blag** [comment]
I don't think `dismissAddAnotherPopup` should be redefined anywhere, so this looks more like a workaround than a fix.
