### ISSUE TITLE
Problem in using django-smart-selects the TabularInline or StackInline

### ISSUE THREAD

**Issue by rodolfo73** [digi604/django-smart-selects#27]
For example, when using django-smart-selects the TabularInline in the admin.py class is inline with the "extra = 3" when I add a new account will appear three lines to be filled in these lines django-smart-selects will work, but if you add a new row it does not work anymore. This is the way you are doing bind the event in JS.

**Comment by SalahAdDin** [comment]
Anyone could solve this issue? Many people have it!

**Comment by gbonvehi** [comment]
I've got this working on PR #96 if you can please test it. Thanks!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by vitorfragoso** [comment]
Any news? Thanks!

**Comment by blag** [comment]
Should be fixed by #148, PyPI release inbound (today or tomorrow).

Closing, but feel free to reopen if it's not. Thanks!
