### ISSUE TITLE
Compatibility issue with django-ajax-selects

### ISSUE THREAD

**Issue by pomarec** [digi604/django-smart-selects#32]
I'm currently using django-ajax-selects for the chained_field. When I change the value of the chained_field, the ChainedForeignKey isn't updated. Would it be possible to have it working ?
Thank you.

**Comment by blag** [comment]
Can you post any debugging information you collected? Your models/forms/admin? Django version? It's impossible to debug issues without any error information.

**Comment by blag** [comment]
I assume this is fixed in [django-ajax-selects PR #59](https://github.com/crucialfelix/django-ajax-selects/pull/59#issue-23897309). Closing.
