### ISSUE TITLE
how about ManyToManyField filtering

### ISSUE THREAD

**Issue by gabejackson** [digi604/django-smart-selects#4]
Could we extend this to support filtering of ManyToManyFields as well? For example a class Wine could be related to grapes via a ManyToManyField and if the user selects a winetype, it will automatically filter the grapes in the multi-select field to show only those of the given winetype (red, white, etc)..

I love this component - thanks for your great work!

Greetings from Switzerland,

Gabe

**Comment by jimmykobe1171** [comment]
It is included in the release 1.2.0 :)
