### ISSUE TITLE
Don't sort the results in the views

### ISSUE THREAD

**Issue by stratoukos** [digi604/django-smart-selects#46]
As it stands right now, smart_selects' views sort the result queryset lexicographically before sending it to the browser. This behavior cancels any custom ordering defined in the model's `Meta.ordering`. 

You could stop sorting the queryset in the view, since anyone who wants the above behavior could specify so in `Meta.ordering`

This would break backwards compatibility for people depending on smart_selects' sorting, so it could be controlled by a setting.

**Comment by blag** [comment]
Should be implemented in 3ffc87d0d99dc778c0ad3ce47608860820b7da86. PyPI release should happen later today or tomorrow. Ping me if I forget! 😄
