### ISSUE TITLE
empty_label is ignored

### ISSUE THREAD

**Issue by dmoisset** [digi604/django-smart-selects#5]
On ModelChoiceFields you can set an empty_label instead of the default '---------'. On smart-selects the '---------' is hardcoded and empty_label is ignored

**Comment by mpena2099** [comment]
@dmoisset, where is your pull request?

**Comment by blag** [comment]
@mpena2099 Why are you digging up an issue and PR that's been closed for 7 years?

His PR is here: https://github.com/digi604/django-smart-selects/pull/6

If you are also having this issue please open a new issue and/or a new PR.

**Comment by mpena2099** [comment]
@blag, because I was not sure if that pull request was accepted, and I'm having a similar problem right now.
