### ISSUE TITLE
JSON response get cache in Internet Explorer 10

### ISSUE THREAD

**Issue by cimadawa** [digi604/django-smart-selects#52]
Hi,

JSON response get cache in IE 10 browsers. Due to this caching, DB data updates are not shown in IE 10 browses. 

I temporarily fixed this by adding "@never_cache" caching control header (https://docs.djangoproject.com/en/dev/topics/cache/#controlling-cache-using-other-headers) to "filterchain" and "filterchain_all" views. please fix this issue.

Thank you.

**Comment by blag** [comment]
Should be fixed in master and I should push a release with the fix out to PyPI within a few days.
