### ISSUE TITLE
Error running syncdb

### ISSUE THREAD

**Issue by bitfhacker** [digi604/django-smart-selects#57]
Hi!

I have python 3.3 and django 1.6. When I'm running syncdb this error occurs;

  File "C:\Python33\lib\site-packages\django_smart_selects-1.0.9-py3.3.egg\smart_selects\db_fields.py", line 19, in __init__
NameError: global name 'basestring' is not defined

I'm following this example:
http://nickbewley.com/development/chained-select-boxes-in-django/

In other machine, with python 2.7 and django 1.6 this runs fine.

**Comment by SalahAdDin** [comment]
I have a same error, could you solved it?

**Comment by bitfhacker** [comment]
Sadly, no. I switched to python 2.7.

**Comment by SalahAdDin** [comment]
Ah, i can solve it using a fork: here https://github.com/digi604/django-smart-selects/issues/63

**Comment by jimmykobe1171** [comment]
fixed in new release 1.1.1
