### ISSUE TITLE
limit_choices_to on ChainedForeignKey?

### ISSUE THREAD

**Issue by Japje** [digi604/django-smart-selects#58]
Hello,

Is it possible to use limit_choises_to on a ChainedForeignKey?

My model:

	datacenter = models.ForeignKey(Datacenter)
	rack = ChainedForeignKey(
		Rack, 
		chained_field="datacenter",
		chained_model_field="datacenter", 
		show_all=False, 
		auto_choose=True
	)
	device = ChainedForeignKey(
		Device, 
		chained_field="rack",
		chained_model_field="rack", 
		show_all=False, 
		auto_choose=True
	)	
	interface = ChainedForeignKey(
		Interface, 
		chained_field="device",
		chained_model_field="device", 
		show_all=False, 
		auto_choose=True,
		limit_choices_to={'cable': None},
	)

Im trying to limit the interfaces to only show interfaces without a cable (FK). But this does not appear to be working.

Gr,

Jasper

**Comment by halfnibble** [comment]
I ended up writing my own model manager after going through the source code, and seeing an option to set a manager for the form field queryset. So, my custom manager filters for the field. However, the db_field does *not* have an option to pass the manager! Therefore, I had to create a form field instance from scratch.

**Comment by halfnibble** [comment]
Please prioritize adding `limit_choices_to` field to the list of parsed fields. Or...should I make a pull request? (I probably can't get to it for at least a week though).

**Comment by jimmykobe1171** [comment]
I will check this issue this week, thanks.

**Comment by jimmykobe1171** [comment]
Hi all,

I have add limit_choices_to support for ChainedForeignKey.

Noted that this changes have not been published to pypi yet.

Best,
Jimmy

**Comment by jimmykobe1171** [comment]
should be ok in release 1.2.0 :)
