### ISSUE TITLE
Remove JQuery from Widget media

### ISSUE THREAD

**Issue by lpalomo** [digi604/django-smart-selects#59]
I see that you are loading JQuery with the widget media. I wonder if this is the ideal thing to do because, I think, there is a huge possibility that JQuery have already been loaded before on the template and therefore JQuery would be downloaded multiples times. What do you think?, maybe saying in the docs that JQuery must be loaded before the widget would be enough.

**Comment by webknjaz** [comment]
https://github.com/digi604/django-smart-selects/issues/135#issue-161036050

**Comment by blag** [comment]
Done in f474f47874cda15fb2a58a90473530b81ab73ce5.

```python
JQUERY_URL = False
```

Closing.
