### ISSUE TITLE
Inline chained select issues 

### ISSUE THREAD

**Issue by deschepper** [digi604/django-smart-selects#60]
I am using django 1.6 and django-smart-selects 1.0.9. I don't seem to be able to get the chained select box to get updates without submitting the form. 
# In models.py I have the following :

``` python
class Product(models.Model):
    name = models.CharField(max_length=127,unique=True)

class Component(models.Model):
    name = models.CharField(max_length=126)
    product = models.ForeignKey(Product,blank=False)

class License(models.Model):
    product = models.ForeignKey(Product)
    component = ChainedForeignKey(Component,chained_field="product",
                                  chained_model_field="product",
                                  show_all=False, auto_choose=True)

class LicenseForm(forms.ModelForm):    
    class Meta:
        model = License
        fields = '__all__'
```
# In admin.py I then have:

``` python
class LicenseInline(admin.StackedInline):
    model = models.License
    form = models.LicenseForm
    extra = 0

class LicenseAdmin(admin.ModelAdmin):
    list_select_related = True
    list_display = ('product','component')
    list_filter = ['product__name']
    list_display_links = ('product', 'component')

class LicenseFileAdmin(admin.ModelAdmin):
    form = models.LicenseFileForm
    inlines = [LicenseInline]
```

If I go to add a new license directly in the administration interface, the product and component boxes are correctly chained. If I add a new license in the inline form, selecting the product does not change the selection in the component box (in fact, it remains empty). If I select a product and then click to add another license, a second license form is shown, which has the correct component selection for the product of the previous form. Changing the product does not change the selection in this form either, though.  

Selecting a product does cause a GET from the chaining URL, which returns the correct selection of the component for the product, but this selection simply isn't used to update the form. The returned value is identical for the inlined version and the standalone version of the license form.

Edit by blag: Formatted code with Markdown.

**Comment by jimmykobe1171** [comment]
Hi, does this issue still occur ? Maybe you can try update to the latest version 1.1.1.

**Comment by blag** [comment]
This is probably fixed in #148. Can you test against the master branch? Thanks!

**Comment by minholi** [comment]
I'm having the same problem using version 1.2.5 (master) with django 1.10

**Comment by blag** [comment]
@minholi I just pushed version 1.2.6 out to PyPI, and it should fix this. Please test this and comment/reopen this issue if it isn't fixed.
