### ISSUE TITLE
Self referential ForeignKeys not defined

### ISSUE THREAD

**Issue by crackjack** [digi604/django-smart-selects#64]
I have a requirement where I need to list all the persons belonging to a particular category, I get error while trying to do so.

class Person(models.Model):
	category = models.CharField()
	parent = ChainedForeignKey(self, chained_field="category", chained_model_field="category", show_all=False, auto_choose=True)

Am  I missing anything here?

**Comment by SalahAdDin** [comment]
You need create a Category Model.

**Comment by Turbid** [comment]
I confirm this. For code:
```
class Subdivision(models.Model):
    affiliate = ForeignKey(Group)
    parent = ChainedForeignKey("self", chained_field="affiliate", chained_model_field="affiliate",
                               show_all=False, auto_choose=True, null=True, blank=True, related_name="subdivisions")
    subdivision = CharField(verbose_name="subdivision", max_length=255)
```
I got this errror:
```
File "..\Python35\lib\site-packages\smart_selects\db_fields.py", line 154, in __init__
    self.to_app_name, self.to_model_name = to.split('.')
ValueError: not enough values to unpack (expected 2, got 1)
```
Because "self" have not '.' for split
