### ISSUE TITLE
Support for foreign characters???

### ISSUE THREAD

**Issue by Chez** [digi604/django-smart-selects#7]
I have just installed django-smart-selects...and have found two
immediate issues:

1. On your example for GroupedForeignKey, you precede  this with model.GroupedForeignKey,
this needs to be just GroupedForeignKey.

2. Your chaining doesn't like foreign characters it seems....I have a
region in Turkey in a select box. On selection of a region I want to
change the content of the cities select box. But regions with foreign
characters, such as  Muğla, although they show up in the regions select
box, on selection, do not  change the contents of cities, however, Mugla
(with a normal 'g') does.

**Comment by blag** [comment]
Closing since it's been so long. If you are still having the same issue feel free to reopen.
