### ISSUE TITLE
Releasing updated version to PyPi

### ISSUE THREAD

**Issue by kegan** [digi604/django-smart-selects#75]
Just want to point out that a lot of the bug fixes in 2014 has not been officially release to PyPi yet.

I have to remember to get from the latest branch everytime, "pip install git.xx.xxx.". This is ok. But it may prevent developers that are new to the library from adopting.

Any reason that is preventing the release? How can we help?

**Comment by gamesbook** [comment]
Yes; a new version would help a lot - Django 1.8 (LTS) is now out and that would be a good version to support.

**Comment by digi604** [comment]
anybody wants to take over as maintainer?

**Comment by halfnibble** [comment]
I'd like to second @digi604's request for a new maintainer. We can't even use pip requirements without an updated PyPi. 

I'll give $20 USD to the first volunteer. ;-)

**Comment by digi604** [comment]
@jimmykobe1171 has taken over as maintainer... a new version should appear on pypi soon.
