### ISSUE TITLE
Search for new maintainer.

### ISSUE THREAD

**Issue by digi604** [digi604/django-smart-selects#80]
If you are interested in taking over this project please contact me.

**Comment by jimmykobe1171** [comment]
Hi, I am interested in this project, how can I contribute to it ?

**Comment by digi604** [comment]
Hi Jimmy,

I need someone how takes over the project... merges the pull requests, publishes new versions to pypi etc.

**Comment by jimmykobe1171** [comment]
I am willing to do this, what do I need to do first ?

**Comment by SalahAdDin** [comment]
:+1: Please, put to @jimmykobe1171 as new project manager :D

**Comment by SalahAdDin** [comment]
Wow, so good, thank you :D
