### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by thecristen** [digi604/django-smart-selects#85]
Hi, I'm using 1.1.1 and have not specified any alternative jQuery location. Why can't it find jQuery?

**Comment by jimmykobe1171** [comment]
If you do not specify USE_DJANGO_JQUERY and JQUERY_URL in setttings.py, it will use 'http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js' by default. Have this file been loaded ?

**Comment by thecristen** [comment]
Nope, it has not been loaded as far as I can tell.

**Comment by SalahAdDin** [comment]
Put ```USE_DJANGO_JQUERY = False```, otherwise you will have one error in the server, ```collecstatic``` can't find admin/js and raise a error. This happen's me.

I think that this option will be deprecated.

**Comment by thecristen** [comment]
Thanks both for your assistance. I tried messing with the settings but in the end I left the settings alone and used the jquery used by the rest of my app (in the base template). Once I moved the jquery script to the top of the page (it was at the bottom before), I stopped getting that error and it worked fine. :)

**Comment by SalahAdDin** [comment]
Interesting man, very interesting, and strange.

**Comment by halfnibble** [comment]
I use my own jQuery as well--you don't want to load an old jQuery. I also had to place it at the top.
