### ISSUE TITLE
Problem with the values returned by smart-selects

### ISSUE THREAD

**Issue by VSandSH** [digi604/django-smart-selects#88]
The values in my smart-selects are in cyrillic text. I have 2 chained smart selects: Region -> City. Whenever in my views.py I try to check whether the selected value in City field is one of the specific available values `if (city == u'Все' )`, I get `False`. But it passes the check when I do the following: `if (city == City.objects.get(id=12) )`. 
Since, `'Все'` is present in every City table that is chained to Region, the comparison statement becomes `if (city == City.objects.get(id=12) or city == City.objects.get(id=18) or city == City.objects.get(id=22) )` assuming Region table has 3 entries. 

The comparison works with English text but not with Cyrillic. Are there any solutions which don't use fields' IDs but just text?

**Comment by jimmykobe1171** [comment]
Hi VSandSH,

I am not sure it is right to compare your City field with string, say `if (city == u'Все' )`. In my opinion, if you want to compare two model in django, compare their id, say `if (city1.id == city2.id)`.

**Comment by VSandSH** [comment]
Thank you jimmykobe1171, the thing here is not to compare fields of the two models but to check whether the dropdown field is set to a specific value. The problem here is, for example, when I write  `if (city == 'all')` the check passes, but when I write `if (city == u'Bce')` it doesn't, so in order to make it work with Cyrillic text, the trick with field's IDs can be used. But in the case when there's many IDs associated with the field, it makes the code look ugly. Say, if there are dozens of IDs, the comparison statement then needs to be written dozens time. My question was how to eliminate comparison with all the IDs and just use one `if` statement?

**Comment by blag** [comment]
This appears to be an issue with comparing a models string representation with a string and not an issue with DSS itself. Closing.
