### ISSUE TITLE
Having chained fk in list_editable always triggers "You have unsaved changes..." message when trying to execute admin action

### ISSUE THREAD

**Issue by mkaluza** [digi604/django-smart-selects#91]
And I don't mean after changing something - simply opening a list view that enables editing a chained fk and trying to execute any action shows this message. From a breif time I spent investigating (I'm using mostly android tablet and therefore have no sensible way of debugging javascript live) I've found that the creation/refresh of a chained FK field triggers django's "changed" flag which doesn't check if the value really changed.

**Comment by gbonvehi** [comment]
@mkaluza it might have to do with #95 , I found this error while using smart-selects with django-suit which has a modify checker on unload.

**Comment by mkaluza** [comment]
nope. it's this https://github.com/gbonvehi/django-smart-selects/blob/master/smart_selects/widgets.py#L148
and it's fixed with this https://github.com/mkaluza/django-smart-selects/commit/2820c7590c6f757c412cad3986466e82bfcacb62

by the way - your external js stuff is great - imho it's the way to go!  I've added a few things:
https://github.com/mkaluza/django-smart-selects/commits/js-external-with-inline
only one is missing right now (issue #92) which I have solved here https://github.com/mkaluza/django-smart-selects/commit/39c8747161d6abd7b8161542f69ef49ab0bd56c4 but haven't ported to your branch yet. Once I did it - I switch and vote for merging your branch upstream

**Comment by gbonvehi** [comment]
@mkaluza thanks! I've just created the pull request, if it's merged we can then improve it there. Hope it is as chained within inlines is really helpful

**Comment by blag** [comment]
This should be fixed when b074ebb334c32c1f535a9134a05798b80d4d773c is tested and merged into master.

**Comment by blag** [comment]
I just released version 1.2.6 to PyPI and it should fix this. Please test and reopen this issue if it still happens. Thanks!
