### ISSUE TITLE
Allow spanning multiple relations

### ISSUE THREAD

**Issue by mkaluza** [digi604/django-smart-selects#93]
This issue is more to begin a discussion that get a sollution - I need thi stuff so I make it my side projecct anyway, but I'd like at least author's comment so in the future my solution could be merged upstream to benefit others.

Current status is:

``` python
class A(Model):
        pass

class B(Model):
        a = ForeignKey(A)

class Main(Model):
        main_a = ForeignKey(A)
        b = ChainedForeignKey(B, chained_field = "main_a", chained_model_field = "a")
```

What I want to make possible is:

``` python
class A(Model):
        pass

class B(Model):
        a = ForeignKey(A)

class C(Model):
        a = ForeignKey(A)

class D(Model)
        c = ForeignKey(C)

class Main(Model):
        b = ForeignKey(B)
        d = ChainedForeignKey(D, chained_field = "b__a", chained_model_field = "c__a")
```

Which I imagine would result in a filter of a kind `D.filter(c__a = self.b.a)` and it's variants depending on the kind of intermediate relations (m2m, o2m, m2o, etc). Most (all?) changes probably would need to be made in widgets.py in [_get_available_choices](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L213) and around [javascript in render](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L177). Right now I have little idea about how django forms work so if my thinking is wrong, please point me somewhere in the right direction ;) But I intend to expand my understanding of this stuff because sooner or later it'll hit me anyway :P

**Comment by olivierdalang** [comment]
Hi,

Here I have "Files", that have several "Quotations" and several "Constructions".
Each "Construction" has a foreign key to its base "Quotation".

Currently, I display both "Constructions" and "Quotations" as inlines in my "File" admin form, which is very practical, but I want the user to be able to select only a "Quotation" that belongs to the same "File".

Is that what you're trying to solve? If so, that would be great ;) I need it for my project too, and would maybe give it a shot if I get the time.
Any workaround in the mean time ?

Bests,

Olivier

**Comment by imaia** [comment]
+1 This feature would also be very helpful to me

**Comment by blag** [comment]
Pull #94 is a good start on fixing this, but being able to query across an arbitrary number of model boundaries would be better.

**Comment by blag** [comment]
As I explained in #94, this is a security incident waiting to happen, so I won't be accepting any PRs implementing this unless somebody can come up with a secure by default access control. Sorry!
